name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update README with LeetCode stats
        uses: tibdex/github-profile-leetcode-action@v1
        with:
          username: chrysler90
          readme-file: README.md
          commit-message: Update LeetCode stats in README
          commit-user-name: github-actions
          commit-user-email: github-actions@github.com


