name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # Every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: Asia/Manila
          plugin_leetcode: yes
          plugin_leetcode_user: chrysler90
